services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: drive-server
    ports:
      - "8080:8080"
    volumes:
      - ./my_storage_data:/usr/src/app/my_storage
    networks:
      - drive-network
    environment:
      - THREAD_POOL_SIZE=5

  web-server:
    build:
      context: ./web-server
      dockerfile: Dockerfile.webServer
    ports:
      - "5000:5000"
    environment:
      - CPP_SERVER_HOST=server 
      - CPP_SERVER_PORT=8080
      - JWT_SECRET=SecretKeyForJWTs123
    depends_on:
      - server
    networks:
      - drive-network

  client-react:
    build:
      context: ./client-react
    ports:
      - "3000:3000" 
    depends_on:
      - web-server
    networks:
      - drive-network

  client-mobile:
    build:
      context: ./clientMobile
    ports:
      - "8081:8081"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - CI=1
    volumes:
      # This allows changing the .env file without rebuilding
      - ./clientMobile/.env:/app/.env
    depends_on:
      - web-server
    networks:
      - drive-network

networks:
  drive-network:
    driver: bridge