FROM gcc:latest
RUN apt-get update && apt-get install -y cmake
WORKDIR /usr/src/app
COPY . .
RUN mkdir build
WORKDIR /usr/src/app/build
RUN cmake -DCMAKE_TLS_VERIFY=false .. && make run_tests
CMD ["./run_tests"]