export const PERMISSIONS = {
    HEADER_TITLE: 'הרשאות עבור:',
    PERMISSIONS_COUNT: 'הרשאות',
    LOADING_MESSAGE: '...טוען הרשאות',
    ERROR_MESSAGE: 'שגיאה בטעינת הרשאות',
    FORBIDDEN_MESSAGE: 'רק הבעלים יכול לצפות ברשימת ההרשאות',
    NO_PERMISSION_MESSAGE: 'אין לך הרשאה לצפות ברשימת ההרשאות',
    EMPTY_MESSAGE: 'אין הרשאות להצגה',
    RESOURCE_LABEL: 'משאב:',
    ROLE_OWNER: 'בעלים',
    ROLE_WRITER: 'עורך',
    ROLE_READER: 'קורא',
    MENU_BUTTON: 'הרשאות',
    ADD_USER_BUTTON: 'הוסף משתמש',
    ADD_USER_MODAL_TITLE: 'הוסף משתמש להרשאות',
    ADD_USER_PLACEHOLDER: 'שם משתמש (username)',
    ADD_BUTTON: 'הוסף',
    CANCEL_BUTTON: 'ביטול',
    LOADING_BUTTON: '...מעבד',
    ADD_USER_ERROR: 'שגיאה בהוספת משתמש',
    ADD_USER_ERROR_EMPTY: 'נא להזין שם משתמש',
    USER_NOT_FOUND: 'משתמש לא נמצא. ודא ששם המשתמש נכון.',
    USER_NOT_FOUND_HINT: 'משתמש לא נמצא במערכת. ודא שהמשתמש רשום ושהזנת את שם המשתמש המדויק.',
    CHANGE_ROLE_ERROR: 'שגיאה בשינוי הרשאה',
    CHANGE_ROLE_TOOLTIP: 'לחץ לשינוי הרשאה',
    DELETE_PERMISSION_ERROR: 'שגיאה במחיקת הרשאה',
    DELETE_PERMISSION_CONFIRM: 'האם למחוק את ההרשאה עבור',
    DELETE_PERMISSION_TOOLTIP: 'מחק הרשאה',
    CANNOT_DELETE_LAST_OWNER: 'לא ניתן למחוק את הרשאת הבעלים האחרונה. חייב להיות לפחות בעלים אחד לקובץ.',
};
